name: "✨ Feature Request"
description: Suggest a new idea, improvement, or change for No More Pop-ups
title: "[Feature]: "
labels: ["enhancement"]
assignees: ["Alfakynz"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        I love hearing your ideas!
        Please describe the feature you'd like to see added to No More Pop-ups.

  - type: textarea
    id: suggestion
    attributes:
      label: "Describe your feature request"
      description: What would you like to see added or changed?
      placeholder: "Explain your idea clearly."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Additional details or context"
      description: Add any screenshots, references, or examples if relevant.
      placeholder: "Optional: screenshots, or inspiration sources."

  - type: checkboxes
    id: confirmation
    attributes:
      label: "Checklist"
      options:
        - label: "I've checked existing issues to make sure this feature hasn't already been suggested."
          required: true
